[tool.ruff]
lint.select = ["E", "F", "I", "UP"]
line-length = 120
target-version = "py310"
src = ["src"]
lint.isort.known-first-party = ["large_data"]
output-format = "full"

[tool.mypy]
check_untyped_defs = true
python_version = '3.10'
exclude = [".venv/*"]
